# Store non-secret configuration in a ConfigMap resource
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
data:
  database: {{ .Values.postgres.dbname }}
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_USER: {{ .Values.postgres.user }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configfiles
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 4 }}
