apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookkeeper.fullname" . }}
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bookkeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bookkeeper.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ .Release.Name }}-config-volume
        configMap:
          name: {{ .Release.Name }}-configfiles
          defaultMode: 0644
      - name: {{ .Release.Name }}-db-files-volume
        configMap:
          name: {{ .Release.Name }}-db-files
          defaultMode: 0644
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bookkeeper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-postgres # Wait for Postgres to start
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
        - name: {{ .Chart.Name }}-init-flyway # Runthe flyway database migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag | default .Chart.AppVersion }}"
          command: ['sh', '-c', 'cat {{ .Values.flyway.configpath }}; ls {{ .Values.flyway.dbpath }}/migrations; flyway -password=${POSTGRES_PASSWORD} -configFiles={{ .Values.flyway.configpath }} migrate']
          imagePullPolicy: {{ .Values.flyway.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: {{ .Values.flyway.configpath }}
              subPath: flyway.conf
            - name: {{ .Release.Name }}-db-files-volume
              mountPath: {{ .Values.flyway.dbpath }}/migrations
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: /opt/local/bookkeeper/bookkeeper.yml
              subPath: bookkeeper.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
