apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:11-alpine
        #command: [ "su", "-", "postgres", "-c", "postgres -D /opt/local/bookkeeper/postgresql/data" ]
        ports:
        - name: postgres
          containerPort: 5432
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: bookkeeper-volume
          mountPath: "/opt/local/bookkeeper/postgresql/data"
          readOnly: false
        - name: {{ .Release.Name }}-config-volume
          mountPath: /docker-entrypoint-initdb.d/initdb.sh
          subPath: initdb.sh
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: POSTGRES_HOST
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: PGDATA
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database
      restartPolicy: Always
      volumes:
      {{- if and .Values.persistence.enabled .Values.persistence.existingClaimName }}
      - name: bookkeeper-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaimName }}
      {{- else }}
      - name: bookkeeper-volume
        emptyDir: {}
      {{- end }}
      - name: {{ .Release.Name }}-config-volume
        configMap:
          name: {{ .Release.Name }}-configfiles
          defaultMode: 0755

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
