apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookkeeper.fullname" . }}
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: bookkeeper
  selector:
    {{- include "bookkeeper.selectorLabels" . | nindent 4 }}
