--- Note that this is completed in k8s via the Dockerfile
--- or via s shell script in non-k8s development envs
--- Create the Bookkeeper database
--- CREATE DATABASE bookkeeper WITH ENCODING = 'UTF8';